### ISSUE TITLE
Make queue publish wait timeout configurable

### ISSUE THREAD

**Issue by agis** [skroutz/rspecq#18]
Right now the reporter waits 30" for the first worker to boot and publish the queue. Depending on the codebase this might be too much or too little. Therefore, we should make this configurable via the CLI.

https://github.com/skroutz/rspecq/blob/83bd0c082161861a648312c13c93439684d8ca5f/lib/rspecq/queue.rb#L200

**Comment by jfragoulis** [comment]
Done https://github.com/skroutz/rspecq/pull/51
