### ISSUE TITLE
Allow to connect to Redis via url

### ISSUE THREAD

**Issue by 2rba** [skroutz/rspecq#37]
Now the only redis option is a `-r, --redis HOST`
would be good to have URL option as well to be able to specify port and password

**Comment by agis** [comment]
This is going to be fixed by #25. Thanks for reporting it!

**Comment by 2rba** [comment]
cool! thank you

**Comment by danielwestendorf** [comment]
Could we cut a new version of the gem so this can be used? Thanks!

**Comment by agis** [comment]
@danielwestendorf 0.3.0 is now released, which includes your patch.
